STATE_LIST = [
    ('AL', 'ALABAMA'),
    ('AK', 'ALASKA'),
    ('AR', 'ARKANSAS'),
    ('AZ', 'ARIZONA'),
    ('CT', 'CONNECTICUT'),
    ('CO', 'COLORADO'),
    ('CA', 'CALIFORNIA'),
    ('FL', 'FLORIDA'),
    ('GA', 'GEORGIA'),
    ('DC', 'DISTRICT OF COLUMBIA'),
    ('HI', 'HAWAII'),
    ('IA', 'IOWA'),
    ('IN', 'INDIANA'),
    ('ID', 'IDAHO'),
    ('KS', 'KANSAS'),
    ('KY', 'KENTUCKY'),
    ('LA', 'LOUISIANA'),
    ('MO', 'MISSOURI'),
    ('MS', 'MISSISSIPPI'),
    ('MT', 'MONTANA'),
    ('MN', 'MINNESOTA'),
    ('ME', 'MAINE'),
    ('NE', 'NEBRASKA'),
    ('NH', 'NEW HAMPSHIRE'),
    ('NJ', 'NEW JERSEY'),
    ('NY', 'NEW YORK'),
    ('NM', 'NEW MEXICO'),
    ('ND', 'NORTH DAKOTA'),
    ('NC', 'NORTH CAROLINA'),
    ('IL', 'ILLINOIS'),
    ('OR', 'OREGON'),
    ('OH', 'OHIO'),
    ('OK', 'OKLAHOMA'),
    ('PA', 'PENNSYLVANIA'),
    ('MA', 'MASSACHUSETTS'),
    ('RI', 'RHODE ISLAND'),
    ('SC', 'SOUTH CAROLINA'),
    ('SD', 'SOUTH DAKOTA'),
    ('TN', 'TENNESSEE'),
    ('TX', 'TEXAS'),
    ('UT', 'UTAH'),
    ('VA', 'VIRGINIA'),
    ('WV', 'WEST VIRGINIA'),
    ('WI', 'WISCONSIN'),
    ('VT', 'VERMONT'),
    ('NV', 'NEVADA'),
    ('WY', 'WYOMING'),
    ('WA', 'WASHINGTON'),
    ('MI', 'MICHIGAN'),
    ('MD', 'MARYLAND'),
    ('DE', 'DELAWARE')
]