# Generated by Django 4.2.3 on 2023-07-23 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('AL', 'ALABAMA'), ('AK', 'ALASKA'), ('AR', 'ARKANSAS'), ('AZ', 'ARIZONA'), ('CT', 'CONNECTICUT'), ('CO', 'COLORADO'), ('CA', 'CALIFORNIA'), ('FL', 'FLORIDA'), ('GA', 'GEORGIA'), ('DC', 'DISTRICT OF COLUMBIA'), ('HI', 'HAWAII'), ('IA', 'IOWA'), ('IN', 'INDIANA'), ('ID', 'IDAHO'), ('KS', 'KANSAS'), ('KY', 'KENTUCKY'), ('LA', 'LOUISIANA'), ('MO', 'MISSOURI'), ('MS', 'MISSISSIPPI'), ('MT', 'MONTANA'), ('MN', 'MINNESOTA'), ('ME', 'MAINE'), ('NE', 'NEBRASKA'), ('NH', 'NEW HAMPSHIRE'), ('NJ', 'NEW JERSEY'), ('NY', 'NEW YORK'), ('NM', 'NEW MEXICO'), ('ND', 'NORTH DAKOTA'), ('NC', 'NORTH CAROLINA'), ('IL', 'ILLINOIS'), ('OR', 'OREGON'), ('OH', 'OHIO'), ('OK', 'OKLAHOMA'), ('PA', 'PENNSYLVANIA'), ('MA', 'MASSACHUSETTS'), ('RI', 'RHODE ISLAND'), ('SC', 'SOUTH CAROLINA'), ('SD', 'SOUTH DAKOTA'), ('TN', 'TENNESSEE'), ('TX', 'TEXAS'), ('UT', 'UTAH'), ('VA', 'VIRGINIA'), ('WV', 'WEST VIRGINIA'), ('WI', 'WISCONSIN'), ('VT', 'VERMONT'), ('NV', 'NEVADA'), ('WY', 'WYOMING'), ('WA', 'WASHINGTON'), ('MI', 'MICHIGAN'), ('MD', 'MARYLAND'), ('DE', 'DELAWARE')], max_length=32)),
                ('phoneNumber', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=52, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('is_employee', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_notes', models.TextField()),
                ('date_ordered', models.DateTimeField(auto_now=True, verbose_name='date ordered')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='great_frog_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255)),
                ('item_notes', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='great_frog_app.order')),
            ],
        ),
    ]
