# Generated by Django 4.2 on 2023-04-24 22:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=128)),
                ('phoneNumber', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=52, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('dateOrdered', models.DateTimeField(auto_now=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='great_frog_app.customer')),
                ('firstName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firstNames', to='great_frog_app.customer')),
                ('lastName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lastNames', to='great_frog_app.customer')),
            ],
        ),
    ]
