# Generated by Django 4.2 on 2023-04-24 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('great_frog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='great_frog_app.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='firstName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstNames', to='great_frog_app.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lastName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lastNames', to='great_frog_app.customer'),
        ),
    ]
