# Generated by Django 4.2.3 on 2023-07-23 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_frog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
