# Generated by Django 4.2.3 on 2023-07-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_frog_app', '0002_rename_firstname_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.IntegerField(default=11217, max_length=5),
        ),
    ]
