# Generated by Django 4.2 on 2023-04-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_frog_app', '0002_alter_order_email_alter_order_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='firstName',
            new_name='name',
        ),
    ]
