# Generated by Django 4.2 on 2023-04-28 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_frog_app', '0003_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dateOrdered',
        ),
    ]
