# Generated by Django 4.2 on 2023-04-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_frog_app', '0004_remove_order_dateordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateOrdered',
            field=models.DateTimeField(auto_now=True, verbose_name='date ordered'),
        ),
    ]
