# Generated by Django 4.2 on 2023-04-25 13:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_frog_app', '0017_order_customer_alter_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=None, size=None),
            preserve_default=False,
        ),
    ]
